name: Dependency Update and Compatibility Test

on:
  workflow_dispatch: # Manual trigger

jobs:
  test-3-8:
    runs-on: ubuntu-latest
    name: Test and Update for Python 3.8
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install Required Python Packages
      run: pip install requests packaging

    - name: Run Dependency Update Test
      run: python dependency_update_test.py 3.8

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add requirements.txt
        git commit -m "Update requirements.txt for Python 3.8" || echo "No changes to commit"
        git push origin main || echo "No changes to push"

  test-3-9:
    needs: test-3-8
    runs-on: ubuntu-latest
    name: Test and Update for Python 3.9
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install Required Python Packages
      run: pip install requests packaging

    - name: Run Dependency Update Test
      run: python dependency_update_test.py 3.9

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add requirements.txt
        git commit -m "Update requirements.txt for Python 3.9" || echo "No changes to commit"
        git push origin main || echo "No changes to push"

  test-3-10:
    needs: test-3-9
    runs-on: ubuntu-latest
    name: Test and Update for Python 3.10
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10" # Use quotes to ensure correct version parsing

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install Required Python Packages
      run: pip install requests packaging

    - name: Run Dependency Update Test
      run: python dependency_update_test.py 3.10

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add requirements.txt
        git commit -m "Update requirements.txt for Python 3.10" || echo "No changes to commit"
        git push origin main || echo "No changes to push"

  test-3-11:
    needs: test-3-10
    runs-on: ubuntu-latest
    name: Test and Update for Python 3.11
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install Required Python Packages
      run: pip install requests packaging

    - name: Run Dependency Update Test
      run: python dependency_update_test.py 3.11

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add requirements.txt
        git commit -m "Update requirements.txt for Python 3.11" || echo "No changes to commit"
        git push origin main || echo "No changes to push"
